name: CI/CD Deploy to GCP

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT_ID: solodevkit

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker to use GCR
      run: |
        gcloud auth configure-docker

    # Build & Push Auth Service
    - name: Build & Push auth-service image
      run: |
        docker buildx build --platform linux/amd64 \
          -t gcr.io/${{ env.GCP_PROJECT_ID }}/auth-service:latest \
          ./auth-service --push

    # Build & Push Cart Service
    - name: Build & Push cart image
      run: |
        docker buildx build --platform linux/amd64 \
          -t gcr.io/${{ env.GCP_PROJECT_ID }}/cart:latest \
          ./cart --push

    # Build & Push Product Service
    - name: Build & Push product image
      run: |
        docker buildx build --platform linux/amd64 \
          -t gcr.io/${{ env.GCP_PROJECT_ID }}/product:latest \
          ./product --push

    # Build & Push Gateway Service
    - name: Build & Push gateway-service image
      run: |
        docker buildx build --platform linux/amd64 \
          -t gcr.io/${{ env.GCP_PROJECT_ID }}/gateway-service:latest \
          ./gateway-service --push

    # SSH to VM and Deploy
    - name: Deploy on VM via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          # Clone or update repository
          if [ ! -d ~/mercari ]; then
            git clone https://github.com/${{ github.repository }} ~/mercari
          else
            cd ~/mercari && git pull
          fi
          
          # Navigate to repository
          cd ~/mercari
          
          # Check if docker-compose is installed, if not install it
          if ! command -v docker-compose &> /dev/null; then
            echo "Installing docker-compose..."
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          fi
          
          # Pull and run containers
          docker-compose pull
          docker-compose up -d --remove-orphans
